CREATE DATABASE IF NOT EXISTS `edu`;
CREATE DATABASE IF NOT EXISTS `classroom_db`;
CREATE DATABASE IF NOT EXISTS `test_db`;
CREATE DATABASE IF NOT EXISTS `image_db`;
CREATE DATABASE IF NOT EXISTS `textbook_db`;
CREATE DATABASE IF NOT EXISTS `lesson_db`;
